services:
  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
    working_dir: /workspace
    command: sleep infinity
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - mongo
      - redis
      - chroma
      - weaviate

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: memory_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongo:
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7-alpine
    command: [ "redis-server", "--appendonly", "no" ]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  chroma:
    image: ghcr.io/chroma-core/chroma:1.0.0b0
    container_name: chroma
    ports:
      - "8001:8000"
    volumes:
      - chroma-data:/chroma/index
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=FALSE

  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "8080:8080"
    environment:
      - QUERY_DEFAULTS_LIMIT=25
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
    volumes:
      - weaviate-data:/var/lib/weaviate

volumes:
  postgres-data:
  mongo-data:
  weaviate-data:
  chroma-data:
  redis-data:


