version: "3.9"

services:
  dev:
    image: mcr.microsoft.com/devcontainers/python:3.11
    container_name: dev_container
    working_dir: /workspace
    volumes:
      - .:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
    networks:
      - backend
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"

  postgres:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  mongo:
    image: mongo:4.4
    container_name: mongo_container
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend

  redis:
    image: redis:7
    container_name: redis_container
    ports:
      - "6379:6379"
    networks:
      - backend

  chroma:
    image: chromadb/chroma:0.4.22
    container_name: chroma_container
    ports:
      - "8001:8000"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
